trigger:
- master

pool: Default

steps:

- script: dotnet restore
  displayName: dotnet restore

- script: dotnet publish MvcTest
    --no-restore
    --output $(Build.ArtifactStagingDirectory)
  displayName: dotnet publish

- task: AzureRmWebAppDeployment@4
  displayName: Azure App Service deploy
  inputs:
    azureSubscription: nick-azure
    WebAppName: escalona1902test
    packageForLinux: $(Build.ArtifactStagingDirectory)
